### ISSUE TITLE
WarTech Mod Launch Crash

### ISSUE THREAD

**Issue by Feng1Xing2** [WarTechMod/Warfare-Technology-1.7.10-NTM-Addon#5]
After NTM4935 update, there is a crash issue when dragging WarTech Mod into the Mods folder and starting it![Screenshot_20240415_183631.jpg](https://github.com/WarTechMod/Warfare-Technology-1.7.10-NTM-Addon/assets/133725285/77aa7156-2f30-4f05-b2ec-a54fe0575d4e)

**Comment by www12343413434** [comment]
But x4951 can
